TOZ_iOS.xcodeproj/project.pbxproj

Add script for launch SwiftLint at project runtime

Fix for SwiftLint

---

TOZ_iOS/BackendAPIRequest.swift
TOZ_iOS/BackendService.swift

Correct default JSON Headers
Remove redundant global variable didPerformUnauthorizedOperation

Update backend communication

---

TOZ_iOS/AppDelegate.swift
TOZ_iOS/Color.swift

Still have to figure out tableView separator colouring.

Add a part of the app skin management and temporary colours

---

TOZ_iOS/Base.lproj/Main.storyboard
TOZ_iOS/GalleryViewController.swift
TOZ_iOS/HelpViewController.swift

-changed modal segue to present modally
-commented code that is not necessary at the moment but will be used in the future

Fix for warnings in xCode

---

TOZ_iOS/Base.lproj/Main.storyboard
TOZ_iOS/Color.swift
TOZ_iOS/Gallery.storyboard
TOZ_iOS/GalleryEntity.swift
TOZ_iOS/GalleryTableViewCell.swift
TOZ_iOS/GalleryViewController.swift

All corresponding changes are made as it is presented in UX animal list specification:
- deleted 'age' and 'description' variables from 'GalleryEntity' class and corresponding labels
- added 'type' variable in 'GalleryEntity' for displaying type of animal
- changed background color of GalleryTableViewCell
- scaled labels and UIImage in GalleryTableViewCell in MainStoryboard
- added custom button as it is presented in UX specification

Changes corresponding to UX AnimalList specification

---

TOZ_iOS/Help.storyboard
TOZ_iOS/LoginViewController.swift

-add naviBar for “help” storyboard items

Minor changes in LoginViewController

---

TOZ_iOS.xcodeproj/project.pbxproj
TOZ_iOS/Gallery.storyboard
TOZ_iOS/GalleryDetailDataViewController.swift
TOZ_iOS/GalleryDetailModelController.swift
TOZ_iOS/GalleryDetailPhotoViewController.swift
TOZ_iOS/GalleryDetailViewController.swift
TOZ_iOS/GalleryViewController.swift

Implement PageViewController for browsing photos of animals

Gallery detail photos

---

TOZ_iOS.xcodeproj/project.pbxproj
TOZ_iOS/GetSchedule.json
TOZ_iOS/NetworkServiceMock.swift

Add mock for method GET

---

TOZ_iOS.xcodeproj/project.pbxproj
TOZ_iOS/CalendarHelper.swift
TOZ_iOS/WeekdayItem.swift

Add Calendar helper to CalenderViewController
Add WeekdayItem struct to mange dates in request

Add Calendar helper to CalenderViewController

---

TOZ_iOS/BackendConfiguration.swift

...although it responds with various error codes right now.

Set new URL to backend

---

TOZ_iOS.xcodeproj/project.pbxproj
TOZ_iOS/NetworkServiceMock.swift
TOZ_iOS/PostRegistration.json

Added mock for registration with appropriate JSON file

Added mock for registration

---

TOZ_iOS/BackendService.swift
TOZ_iOS/Gallery.storyboard
TOZ_iOS/GalleryDetailDataViewController.swift
TOZ_iOS/GalleryDetailModelController.swift
TOZ_iOS/GalleryDetailPhotoViewController.swift
TOZ_iOS/GalleryDetailViewController.swift

Now caption with picture's number doesn't move together with picture while swiping

Profile picture handling

---

TOZ_iOS/CalendarHelper.swift
TOZ_iOS/CalendarViewController.swift
TOZ_iOS/GetSchedule.json
TOZ_iOS/WeekViewController.swift
TOZ_iOSTests/CalendarResponseMapperTests.swift

Connect CalendarHelper
Add more get schedule json mock date

Connect calendar helper to UI

---

TOZ_iOS/GalleryDetailViewController.swift

...as suggested in comment to previous pull request.

Fix for GalleryDetailViewController

---

TOZ_iOS/GetNews.json

...to show that NewsViewController handles it appropriately.

Remove photoUrl from one of the mocked news

---

TOZ_iOS/BackendService.swift
TOZ_iOS/News.storyboard
TOZ_iOS/NewsCellContentView.swift
TOZ_iOS/NewsViewController.swift

News background list layout  color and margin

News background list layout color

---

TOZ_iOS/News.storyboard

Pinned scroll view to navi bar bottom instead of top of whole view.

Changed date font size from 8 to 10 in news list.

---

TOZ_iOS/AddScheduleOperation.swift
TOZ_iOS/AddScheduleRequest.swift
TOZ_iOS/BackendAPIRequest.swift
TOZ_iOS/BackendService.swift
TOZ_iOS/GetScheduleWeekOperation.swift
TOZ_iOS/WeekViewController.swift

add Content-Type: application/json -> 415 Unsupported Media
type error with JSON

add ownerId in reservationRequestView request

---

TOZ_iOS/AddScheduleRequest.swift
TOZ_iOS/AnimalRequest.swift
TOZ_iOS/BackendAPIRequest.swift
TOZ_iOS/BackendService.swift
TOZ_iOS/CalendarWeekRequest.swift
TOZ_iOS/ChangePasswordRequest.swift
TOZ_iOS/GetScheduleRequest.swift
TOZ_iOS/ListOfAnimalsRequest.swift
TOZ_iOS/NewsRequest.swift
TOZ_iOS/NewsResponseMapper.swift
TOZ_iOS/OrganizationInfoRequest.swift
TOZ_iOS/ResetPasswordRequest.swift
TOZ_iOS/SignInRequest.swift
TOZ_iOS/SignUpRequest.swift

To get news sorted, query: `?isOrdered=true` must be added to backend request: [link to backend](http://dev.patronage2017.intive-projects.com/api/news?isOrdered=true).

News order and add query items to requests

---

TOZ_iOS.xcodeproj/project.pbxproj
TOZ_iOS/AnimalGalleryItem.swift
TOZ_iOS/AnimalItem.swift
TOZ_iOS/AnimalResponseMapper.swift
TOZ_iOS/GalleryDetailViewController.swift
TOZ_iOS/GetPetByID.json
TOZ_iOS/ListOfAnimalsArrayResponseMapper.swift
TOZ_iOS/NewsResponseMapper.swift

Handle gallery returned from backend.

Gallery for animal profile

---

TOZ_iOS/Help.storyboard
TOZ_iOS/SignUpViewController.swift

SignUpVC:
*move title to navigation bar
*remove cancel button
*change scrollview inset when keyboard will show/ will hide

SignUpVC fix

---

TOZ_iOS/Account.storyboard
TOZ_iOS/ResetPasswordViewController.swift

Changed old indicatorView to progressHud

Moved title from view to navigation bar
